# Generated by Django 5.1.1 on 2024-12-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_games_alter_student_age_alter_student_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='game',
        ),
    ]
